use_frameworks!

platform :ios, '9.0'

target 'LYNetManager_Example' do
  pod 'LYNetManager', :path => '../'

  target 'LYNetManager_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
